# Site settings
title: Kit Noussis
email: c.noussis at gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I'm Christopher Noussis and this is my blog. I am a Canadian Undergraduate student at Quest University Canada.
    Some of my interests are data science, machine learning, A.I., and jazz.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kitnoussis
github_username: KitN 

# Build settings
markdown: kramdown
